
[main]

    x = 10
    key3 = "value3"

    [sub_dict]

        key1 = "value1"
        key2 = "value2"

[another_dict]

    y = 20

    [nested_dict]

        nested_key1 = "nested_value1"